### PR TITLE
Rewrite class file parser to nom

### PR DESCRIPTION
**Pull request by CertainLach**
> nom is a parser combinator library with a focus on safe parsing, streaming patterns, and as much as possible zero copy.

A lot of work still needs to be done, this code currently won't compile
After rewriting we can consider extracting parser to another repo

### CODE REVIEW

**Comment by douchuan** [comment]
excellent, just do it

**Review by douchuan — APPROVED** [review]

**Comment by CertainLach** [comment]
Everything is done, class parser needs tests though

**Comment by CertainLach** [comment]
I think @JarvisCraft can help us with tests soon

**Comment by douchuan** [comment]
> I think @JarvisCraft can help us with tests soon

ok, there is no a good class file parser in crates.io,
Let's do our best to finish it.

**Comment by douchuan** [comment]
I'v merged, it doesn't work yet

**Comment by douchuan** [comment]
what about switch to functions instead of macros ?

Doc from [nom:](https://docs.rs/nom/5.1.1/nom/?search=)
> 

nom has used macros for combinators from versions 1 to 4, and from version 5, it proposes new combinators as functions, but still allows the macros style (macros have been rewritten to use the functions under the hood). For new parsers, we recommend using the functions instead of macros, since rustc messages will be much easier to understand.

**Comment by douchuan** [comment]
There are 2 small bugs, fixed.


1. update index error when parsing constant pool

2.  missing full_frame

**Pull request merged**
